### ISSUE TITLE
버튼 클래스 추가가 필요해 보임

### ISSUE THREAD

**Issue by scjang** [seoulstore/ssss#37]
<img width="85" alt="screen shot 2018-01-23 at 18 46 47" src="https://user-images.githubusercontent.com/8815372/35268895-cfc21dda-006d-11e8-89ed-24e433844817.png">

- .btn-black (?)

**Comment by afr5** [comment]
`btn-reverse` 라고 있을텐데?

**Comment by scjang** [comment]
@afrobambacar 있어요!!!!!
